services:
  - type: web
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENGAGE_DIGITAL_ACCESS_TOKEN
        sync: false
      - key: ENGAGE_DIGITAL_SERVER
        sync: false
